# config.py example
DEFAULT_LLM = 'ollama'
OAI_KEY = 'your_oai_key'
OAI_LLM = 'gpt-4'
OLLAMA_URL = 'http://localhost:11434/' 
OLLAMA_LLM = 'gpt-oss:20b'
GROK_KEY = 'your_grok_key'
GROK_LLM = 'grok-4'
NEWS = 'https://example.com/news/rss'
